import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  output: "export",
  trailingSlash: true,
  images: {
    // Static export has no image optimization server, so instead of `unoptimized: true`
    // (which ships every original file at full size with no srcset) we point next/image
    // at WebP variants pre-generated by scripts/generate-images.js.
    loader: "custom",
    loaderFile: "./lib/image-loader.ts",
    // These two lists are the complete set of widths next/image may request, and must
    // stay in sync with WIDTHS in scripts/generate-images.js.
    deviceSizes: [640, 828, 1080, 1920],
    imageSizes: [256, 384],
  },
};

export default nextConfig;
